### ISSUE TITLE
Packets not logging correctly?

### ISSUE THREAD

**Issue by Ameliaaaaaaa** [janispritzkau/mcproto#4]
For some reason it's not logging all packets. Not sure if it's something I've done wrong or not.
It logs when I join the server (0x0) but thats that.

	const { PacketWriter, Server, Client } = require('mcproto');

	const server = new Server(async client => {
    	client.on('error', error => {
        	console.log(error);
    	});

    	const handshake = await client.nextPacket();

    	const protocol = handshake.readVarInt();

    	client.pause();

    	let player;

    	try {
        	player = await Client.connect('3b3t.uk', 10014);
    	} catch (e) {
        	console.log(e);
        	return client.end();
    	}

    	player.send(new PacketWriter(0x0).writeVarInt(protocol).writeString('3b3t.uk').writeUInt16(10014).writeVarInt(client.state));

    	player.on('error', error => {
        	console.log(error);
    	});

    	client.on('packet', packet => {
        	player.send(packet);
        	console.log(`[S] 0x${packet.id.toString(16)}`);
    	});

    	player.on('packet', packet => {
        	console.log(`[C] 0x${packet.id.toString(16)}`);
    	});

    	await client.resume();
    	client.unpipe();
    	player.unpipe();

    	client.socket.pipe(player.socket, { end: true });
    	player.socket.pipe(client.socket, { end: true });

	});

	server.listen(25561).then(() => {
    	console.log('Server Started.');
	});

**Comment by janispritzkau** [comment]
This is supposed to happen. I didn't document it properly. When you call `.unpipe()` on the connection, you're basically disabling all packet processing functionality.

To decode all packets, you need to handle authentication in your proxy. There is an example of how to do this, in the examples folder of the repo.
 https://www.github.com/janispritzkau/mcproto/tree/master/examples/proxy.ts

**Comment by Ameliaaaaaaa** [comment]
I've parsed what I needed without needing to do any of the authentication. Thanks.
