### ISSUE TITLE
Keep alive for older versions

### ISSUE THREAD

**Issue by mdashlw** [janispritzkau/mcproto#6]
Current keep alive implementation ([server](https://github.com/janispritzkau/mcproto/blob/5642c105c865a261a958f4b6f1114f60ce2ded47/src/server.ts#L128), [client](https://github.com/janispritzkau/mcproto/blob/5642c105c865a261a958f4b6f1114f60ce2ded47/src/client.ts#L67)) assumes the id is `Int64`, but that's not the case for old versions.
Data extracted from https://github.com/PrismarineJS/minecraft-data:
```js
keepAliveC {
  '1.7': '1.7.2 / 4 / i32',
  '1.8': '1.8 / 47 / varint',
  '1.12': '1.12.2 / 340 / i64'
}
keepAliveS {
  '1.7': '1.7.2 / 4 / i32',
  '1.8': '1.8 / 47 / varint',
  '1.12': '1.12.2 / 340 / i64'
}
```
Not sure of a proper implementation, maybe methods in `packet.ts` to read/write keep alive ids or `PacketReader.readKeepAliveID` + `PacketWriter.writeKeepAliveID`

**Comment by janispritzkau** [comment]
Oh, I didn't read it properly. Alternatively, you can turn it off in the client/server options and handle the keep-alive packets yourself. I only added it for convenience in the first place.

**Comment by janispritzkau** [comment]
I think it might be better if I remove this feature entirely in version 0.6.0. This way I would make maintaining this package easier.

**Comment by janispritzkau** [comment]
I think this is what I will do. I should also update the examples to show how you can implement keep alive.

**Comment by mdashlw** [comment]
I think this would be the simplest and therefore the best solution. It would also allow full flexibility, especially on the server side (defining the keep alive id mechanism, custom interval, whether responding with wrong id disconnects you).

**Comment by janispritzkau** [comment]
I removed the keep alive option and updated the package in npm. So I'm closing this issue.
